// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nxos

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupBgpRouteControl(ctx *pulumi.Context, args *LookupBgpRouteControlArgs, opts ...pulumi.InvokeOption) (*LookupBgpRouteControlResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupBgpRouteControlResult
	err := ctx.Invoke("nxos:nxos/getBgpRouteControl:getBgpRouteControl", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBgpRouteControl.
type LookupBgpRouteControlArgs struct {
	Asn    string  `pulumi:"asn"`
	Device *string `pulumi:"device"`
	Vrf    string  `pulumi:"vrf"`
}

// A collection of values returned by getBgpRouteControl.
type LookupBgpRouteControlResult struct {
	Asn                string  `pulumi:"asn"`
	Device             *string `pulumi:"device"`
	EnforceFirstAs     string  `pulumi:"enforceFirstAs"`
	FibAccelerate      string  `pulumi:"fibAccelerate"`
	Id                 string  `pulumi:"id"`
	LogNeighborChanges string  `pulumi:"logNeighborChanges"`
	SuppressRoutes     string  `pulumi:"suppressRoutes"`
	Vrf                string  `pulumi:"vrf"`
}

func LookupBgpRouteControlOutput(ctx *pulumi.Context, args LookupBgpRouteControlOutputArgs, opts ...pulumi.InvokeOption) LookupBgpRouteControlResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupBgpRouteControlResult, error) {
			args := v.(LookupBgpRouteControlArgs)
			r, err := LookupBgpRouteControl(ctx, &args, opts...)
			var s LookupBgpRouteControlResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupBgpRouteControlResultOutput)
}

// A collection of arguments for invoking getBgpRouteControl.
type LookupBgpRouteControlOutputArgs struct {
	Asn    pulumi.StringInput    `pulumi:"asn"`
	Device pulumi.StringPtrInput `pulumi:"device"`
	Vrf    pulumi.StringInput    `pulumi:"vrf"`
}

func (LookupBgpRouteControlOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBgpRouteControlArgs)(nil)).Elem()
}

// A collection of values returned by getBgpRouteControl.
type LookupBgpRouteControlResultOutput struct{ *pulumi.OutputState }

func (LookupBgpRouteControlResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBgpRouteControlResult)(nil)).Elem()
}

func (o LookupBgpRouteControlResultOutput) ToLookupBgpRouteControlResultOutput() LookupBgpRouteControlResultOutput {
	return o
}

func (o LookupBgpRouteControlResultOutput) ToLookupBgpRouteControlResultOutputWithContext(ctx context.Context) LookupBgpRouteControlResultOutput {
	return o
}

func (o LookupBgpRouteControlResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupBgpRouteControlResult] {
	return pulumix.Output[LookupBgpRouteControlResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupBgpRouteControlResultOutput) Asn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBgpRouteControlResult) string { return v.Asn }).(pulumi.StringOutput)
}

func (o LookupBgpRouteControlResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupBgpRouteControlResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

func (o LookupBgpRouteControlResultOutput) EnforceFirstAs() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBgpRouteControlResult) string { return v.EnforceFirstAs }).(pulumi.StringOutput)
}

func (o LookupBgpRouteControlResultOutput) FibAccelerate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBgpRouteControlResult) string { return v.FibAccelerate }).(pulumi.StringOutput)
}

func (o LookupBgpRouteControlResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBgpRouteControlResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupBgpRouteControlResultOutput) LogNeighborChanges() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBgpRouteControlResult) string { return v.LogNeighborChanges }).(pulumi.StringOutput)
}

func (o LookupBgpRouteControlResultOutput) SuppressRoutes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBgpRouteControlResult) string { return v.SuppressRoutes }).(pulumi.StringOutput)
}

func (o LookupBgpRouteControlResultOutput) Vrf() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBgpRouteControlResult) string { return v.Vrf }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupBgpRouteControlResultOutput{})
}
