// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nxos

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupBgpGracefulRestart(ctx *pulumi.Context, args *LookupBgpGracefulRestartArgs, opts ...pulumi.InvokeOption) (*LookupBgpGracefulRestartResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupBgpGracefulRestartResult
	err := ctx.Invoke("nxos:nxos/getBgpGracefulRestart:getBgpGracefulRestart", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBgpGracefulRestart.
type LookupBgpGracefulRestartArgs struct {
	Asn    string  `pulumi:"asn"`
	Device *string `pulumi:"device"`
	Vrf    string  `pulumi:"vrf"`
}

// A collection of values returned by getBgpGracefulRestart.
type LookupBgpGracefulRestartResult struct {
	Asn             string  `pulumi:"asn"`
	Device          *string `pulumi:"device"`
	Id              string  `pulumi:"id"`
	RestartInterval int     `pulumi:"restartInterval"`
	StaleInterval   int     `pulumi:"staleInterval"`
	Vrf             string  `pulumi:"vrf"`
}

func LookupBgpGracefulRestartOutput(ctx *pulumi.Context, args LookupBgpGracefulRestartOutputArgs, opts ...pulumi.InvokeOption) LookupBgpGracefulRestartResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupBgpGracefulRestartResult, error) {
			args := v.(LookupBgpGracefulRestartArgs)
			r, err := LookupBgpGracefulRestart(ctx, &args, opts...)
			var s LookupBgpGracefulRestartResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupBgpGracefulRestartResultOutput)
}

// A collection of arguments for invoking getBgpGracefulRestart.
type LookupBgpGracefulRestartOutputArgs struct {
	Asn    pulumi.StringInput    `pulumi:"asn"`
	Device pulumi.StringPtrInput `pulumi:"device"`
	Vrf    pulumi.StringInput    `pulumi:"vrf"`
}

func (LookupBgpGracefulRestartOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBgpGracefulRestartArgs)(nil)).Elem()
}

// A collection of values returned by getBgpGracefulRestart.
type LookupBgpGracefulRestartResultOutput struct{ *pulumi.OutputState }

func (LookupBgpGracefulRestartResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBgpGracefulRestartResult)(nil)).Elem()
}

func (o LookupBgpGracefulRestartResultOutput) ToLookupBgpGracefulRestartResultOutput() LookupBgpGracefulRestartResultOutput {
	return o
}

func (o LookupBgpGracefulRestartResultOutput) ToLookupBgpGracefulRestartResultOutputWithContext(ctx context.Context) LookupBgpGracefulRestartResultOutput {
	return o
}

func (o LookupBgpGracefulRestartResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupBgpGracefulRestartResult] {
	return pulumix.Output[LookupBgpGracefulRestartResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupBgpGracefulRestartResultOutput) Asn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBgpGracefulRestartResult) string { return v.Asn }).(pulumi.StringOutput)
}

func (o LookupBgpGracefulRestartResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupBgpGracefulRestartResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

func (o LookupBgpGracefulRestartResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBgpGracefulRestartResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupBgpGracefulRestartResultOutput) RestartInterval() pulumi.IntOutput {
	return o.ApplyT(func(v LookupBgpGracefulRestartResult) int { return v.RestartInterval }).(pulumi.IntOutput)
}

func (o LookupBgpGracefulRestartResultOutput) StaleInterval() pulumi.IntOutput {
	return o.ApplyT(func(v LookupBgpGracefulRestartResult) int { return v.StaleInterval }).(pulumi.IntOutput)
}

func (o LookupBgpGracefulRestartResultOutput) Vrf() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBgpGracefulRestartResult) string { return v.Vrf }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupBgpGracefulRestartResultOutput{})
}
