// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nxos

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupFeatureDhcp(ctx *pulumi.Context, args *LookupFeatureDhcpArgs, opts ...pulumi.InvokeOption) (*LookupFeatureDhcpResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFeatureDhcpResult
	err := ctx.Invoke("nxos:nxos/getFeatureDhcp:getFeatureDhcp", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFeatureDhcp.
type LookupFeatureDhcpArgs struct {
	Device *string `pulumi:"device"`
}

// A collection of values returned by getFeatureDhcp.
type LookupFeatureDhcpResult struct {
	AdminState string  `pulumi:"adminState"`
	Device     *string `pulumi:"device"`
	Id         string  `pulumi:"id"`
}

func LookupFeatureDhcpOutput(ctx *pulumi.Context, args LookupFeatureDhcpOutputArgs, opts ...pulumi.InvokeOption) LookupFeatureDhcpResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupFeatureDhcpResult, error) {
			args := v.(LookupFeatureDhcpArgs)
			r, err := LookupFeatureDhcp(ctx, &args, opts...)
			var s LookupFeatureDhcpResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupFeatureDhcpResultOutput)
}

// A collection of arguments for invoking getFeatureDhcp.
type LookupFeatureDhcpOutputArgs struct {
	Device pulumi.StringPtrInput `pulumi:"device"`
}

func (LookupFeatureDhcpOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFeatureDhcpArgs)(nil)).Elem()
}

// A collection of values returned by getFeatureDhcp.
type LookupFeatureDhcpResultOutput struct{ *pulumi.OutputState }

func (LookupFeatureDhcpResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFeatureDhcpResult)(nil)).Elem()
}

func (o LookupFeatureDhcpResultOutput) ToLookupFeatureDhcpResultOutput() LookupFeatureDhcpResultOutput {
	return o
}

func (o LookupFeatureDhcpResultOutput) ToLookupFeatureDhcpResultOutputWithContext(ctx context.Context) LookupFeatureDhcpResultOutput {
	return o
}

func (o LookupFeatureDhcpResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupFeatureDhcpResult] {
	return pulumix.Output[LookupFeatureDhcpResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupFeatureDhcpResultOutput) AdminState() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureDhcpResult) string { return v.AdminState }).(pulumi.StringOutput)
}

func (o LookupFeatureDhcpResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFeatureDhcpResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

func (o LookupFeatureDhcpResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureDhcpResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFeatureDhcpResultOutput{})
}
