// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nxos

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupFeatureVnSegment(ctx *pulumi.Context, args *LookupFeatureVnSegmentArgs, opts ...pulumi.InvokeOption) (*LookupFeatureVnSegmentResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFeatureVnSegmentResult
	err := ctx.Invoke("nxos:nxos/getFeatureVnSegment:getFeatureVnSegment", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFeatureVnSegment.
type LookupFeatureVnSegmentArgs struct {
	Device *string `pulumi:"device"`
}

// A collection of values returned by getFeatureVnSegment.
type LookupFeatureVnSegmentResult struct {
	AdminState string  `pulumi:"adminState"`
	Device     *string `pulumi:"device"`
	Id         string  `pulumi:"id"`
}

func LookupFeatureVnSegmentOutput(ctx *pulumi.Context, args LookupFeatureVnSegmentOutputArgs, opts ...pulumi.InvokeOption) LookupFeatureVnSegmentResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupFeatureVnSegmentResult, error) {
			args := v.(LookupFeatureVnSegmentArgs)
			r, err := LookupFeatureVnSegment(ctx, &args, opts...)
			var s LookupFeatureVnSegmentResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupFeatureVnSegmentResultOutput)
}

// A collection of arguments for invoking getFeatureVnSegment.
type LookupFeatureVnSegmentOutputArgs struct {
	Device pulumi.StringPtrInput `pulumi:"device"`
}

func (LookupFeatureVnSegmentOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFeatureVnSegmentArgs)(nil)).Elem()
}

// A collection of values returned by getFeatureVnSegment.
type LookupFeatureVnSegmentResultOutput struct{ *pulumi.OutputState }

func (LookupFeatureVnSegmentResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFeatureVnSegmentResult)(nil)).Elem()
}

func (o LookupFeatureVnSegmentResultOutput) ToLookupFeatureVnSegmentResultOutput() LookupFeatureVnSegmentResultOutput {
	return o
}

func (o LookupFeatureVnSegmentResultOutput) ToLookupFeatureVnSegmentResultOutputWithContext(ctx context.Context) LookupFeatureVnSegmentResultOutput {
	return o
}

func (o LookupFeatureVnSegmentResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupFeatureVnSegmentResult] {
	return pulumix.Output[LookupFeatureVnSegmentResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupFeatureVnSegmentResultOutput) AdminState() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureVnSegmentResult) string { return v.AdminState }).(pulumi.StringOutput)
}

func (o LookupFeatureVnSegmentResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFeatureVnSegmentResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

func (o LookupFeatureVnSegmentResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureVnSegmentResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFeatureVnSegmentResultOutput{})
}
