// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nxos

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupIsisInterface(ctx *pulumi.Context, args *LookupIsisInterfaceArgs, opts ...pulumi.InvokeOption) (*LookupIsisInterfaceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupIsisInterfaceResult
	err := ctx.Invoke("nxos:nxos/getIsisInterface:getIsisInterface", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIsisInterface.
type LookupIsisInterfaceArgs struct {
	Device      *string `pulumi:"device"`
	InterfaceId string  `pulumi:"interfaceId"`
}

// A collection of values returned by getIsisInterface.
type LookupIsisInterfaceResult struct {
	AuthenticationCheck   bool    `pulumi:"authenticationCheck"`
	AuthenticationCheckL1 bool    `pulumi:"authenticationCheckL1"`
	AuthenticationCheckL2 bool    `pulumi:"authenticationCheckL2"`
	AuthenticationKey     string  `pulumi:"authenticationKey"`
	AuthenticationKeyL1   string  `pulumi:"authenticationKeyL1"`
	AuthenticationKeyL2   string  `pulumi:"authenticationKeyL2"`
	AuthenticationType    string  `pulumi:"authenticationType"`
	AuthenticationTypeL1  string  `pulumi:"authenticationTypeL1"`
	AuthenticationTypeL2  string  `pulumi:"authenticationTypeL2"`
	CircuitType           string  `pulumi:"circuitType"`
	Device                *string `pulumi:"device"`
	HelloInterval         int     `pulumi:"helloInterval"`
	HelloIntervalL1       int     `pulumi:"helloIntervalL1"`
	HelloIntervalL2       int     `pulumi:"helloIntervalL2"`
	HelloMultiplier       int     `pulumi:"helloMultiplier"`
	HelloMultiplierL1     int     `pulumi:"helloMultiplierL1"`
	HelloMultiplierL2     int     `pulumi:"helloMultiplierL2"`
	HelloPadding          string  `pulumi:"helloPadding"`
	Id                    string  `pulumi:"id"`
	InterfaceId           string  `pulumi:"interfaceId"`
	MetricL1              int     `pulumi:"metricL1"`
	MetricL2              int     `pulumi:"metricL2"`
	MtuCheck              bool    `pulumi:"mtuCheck"`
	MtuCheckL1            bool    `pulumi:"mtuCheckL1"`
	MtuCheckL2            bool    `pulumi:"mtuCheckL2"`
	NetworkTypeP2p        string  `pulumi:"networkTypeP2p"`
	Passive               string  `pulumi:"passive"`
	PriorityL1            int     `pulumi:"priorityL1"`
	PriorityL2            int     `pulumi:"priorityL2"`
	Vrf                   string  `pulumi:"vrf"`
}

func LookupIsisInterfaceOutput(ctx *pulumi.Context, args LookupIsisInterfaceOutputArgs, opts ...pulumi.InvokeOption) LookupIsisInterfaceResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupIsisInterfaceResult, error) {
			args := v.(LookupIsisInterfaceArgs)
			r, err := LookupIsisInterface(ctx, &args, opts...)
			var s LookupIsisInterfaceResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupIsisInterfaceResultOutput)
}

// A collection of arguments for invoking getIsisInterface.
type LookupIsisInterfaceOutputArgs struct {
	Device      pulumi.StringPtrInput `pulumi:"device"`
	InterfaceId pulumi.StringInput    `pulumi:"interfaceId"`
}

func (LookupIsisInterfaceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIsisInterfaceArgs)(nil)).Elem()
}

// A collection of values returned by getIsisInterface.
type LookupIsisInterfaceResultOutput struct{ *pulumi.OutputState }

func (LookupIsisInterfaceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIsisInterfaceResult)(nil)).Elem()
}

func (o LookupIsisInterfaceResultOutput) ToLookupIsisInterfaceResultOutput() LookupIsisInterfaceResultOutput {
	return o
}

func (o LookupIsisInterfaceResultOutput) ToLookupIsisInterfaceResultOutputWithContext(ctx context.Context) LookupIsisInterfaceResultOutput {
	return o
}

func (o LookupIsisInterfaceResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupIsisInterfaceResult] {
	return pulumix.Output[LookupIsisInterfaceResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupIsisInterfaceResultOutput) AuthenticationCheck() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) bool { return v.AuthenticationCheck }).(pulumi.BoolOutput)
}

func (o LookupIsisInterfaceResultOutput) AuthenticationCheckL1() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) bool { return v.AuthenticationCheckL1 }).(pulumi.BoolOutput)
}

func (o LookupIsisInterfaceResultOutput) AuthenticationCheckL2() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) bool { return v.AuthenticationCheckL2 }).(pulumi.BoolOutput)
}

func (o LookupIsisInterfaceResultOutput) AuthenticationKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.AuthenticationKey }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) AuthenticationKeyL1() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.AuthenticationKeyL1 }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) AuthenticationKeyL2() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.AuthenticationKeyL2 }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) AuthenticationType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.AuthenticationType }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) AuthenticationTypeL1() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.AuthenticationTypeL1 }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) AuthenticationTypeL2() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.AuthenticationTypeL2 }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) CircuitType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.CircuitType }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

func (o LookupIsisInterfaceResultOutput) HelloInterval() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) int { return v.HelloInterval }).(pulumi.IntOutput)
}

func (o LookupIsisInterfaceResultOutput) HelloIntervalL1() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) int { return v.HelloIntervalL1 }).(pulumi.IntOutput)
}

func (o LookupIsisInterfaceResultOutput) HelloIntervalL2() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) int { return v.HelloIntervalL2 }).(pulumi.IntOutput)
}

func (o LookupIsisInterfaceResultOutput) HelloMultiplier() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) int { return v.HelloMultiplier }).(pulumi.IntOutput)
}

func (o LookupIsisInterfaceResultOutput) HelloMultiplierL1() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) int { return v.HelloMultiplierL1 }).(pulumi.IntOutput)
}

func (o LookupIsisInterfaceResultOutput) HelloMultiplierL2() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) int { return v.HelloMultiplierL2 }).(pulumi.IntOutput)
}

func (o LookupIsisInterfaceResultOutput) HelloPadding() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.HelloPadding }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) InterfaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.InterfaceId }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) MetricL1() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) int { return v.MetricL1 }).(pulumi.IntOutput)
}

func (o LookupIsisInterfaceResultOutput) MetricL2() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) int { return v.MetricL2 }).(pulumi.IntOutput)
}

func (o LookupIsisInterfaceResultOutput) MtuCheck() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) bool { return v.MtuCheck }).(pulumi.BoolOutput)
}

func (o LookupIsisInterfaceResultOutput) MtuCheckL1() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) bool { return v.MtuCheckL1 }).(pulumi.BoolOutput)
}

func (o LookupIsisInterfaceResultOutput) MtuCheckL2() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) bool { return v.MtuCheckL2 }).(pulumi.BoolOutput)
}

func (o LookupIsisInterfaceResultOutput) NetworkTypeP2p() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.NetworkTypeP2p }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) Passive() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.Passive }).(pulumi.StringOutput)
}

func (o LookupIsisInterfaceResultOutput) PriorityL1() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) int { return v.PriorityL1 }).(pulumi.IntOutput)
}

func (o LookupIsisInterfaceResultOutput) PriorityL2() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) int { return v.PriorityL2 }).(pulumi.IntOutput)
}

func (o LookupIsisInterfaceResultOutput) Vrf() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIsisInterfaceResult) string { return v.Vrf }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIsisInterfaceResultOutput{})
}
