// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nxos

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupOspfVrf(ctx *pulumi.Context, args *LookupOspfVrfArgs, opts ...pulumi.InvokeOption) (*LookupOspfVrfResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupOspfVrfResult
	err := ctx.Invoke("nxos:nxos/getOspfVrf:getOspfVrf", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOspfVrf.
type LookupOspfVrfArgs struct {
	Device       *string `pulumi:"device"`
	InstanceName string  `pulumi:"instanceName"`
	Name         string  `pulumi:"name"`
}

// A collection of values returned by getOspfVrf.
type LookupOspfVrfResult struct {
	AdminState            string  `pulumi:"adminState"`
	BandwidthReference    int     `pulumi:"bandwidthReference"`
	BanwidthReferenceUnit string  `pulumi:"banwidthReferenceUnit"`
	Device                *string `pulumi:"device"`
	Distance              int     `pulumi:"distance"`
	Id                    string  `pulumi:"id"`
	InstanceName          string  `pulumi:"instanceName"`
	Name                  string  `pulumi:"name"`
	RouterId              string  `pulumi:"routerId"`
}

func LookupOspfVrfOutput(ctx *pulumi.Context, args LookupOspfVrfOutputArgs, opts ...pulumi.InvokeOption) LookupOspfVrfResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupOspfVrfResult, error) {
			args := v.(LookupOspfVrfArgs)
			r, err := LookupOspfVrf(ctx, &args, opts...)
			var s LookupOspfVrfResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupOspfVrfResultOutput)
}

// A collection of arguments for invoking getOspfVrf.
type LookupOspfVrfOutputArgs struct {
	Device       pulumi.StringPtrInput `pulumi:"device"`
	InstanceName pulumi.StringInput    `pulumi:"instanceName"`
	Name         pulumi.StringInput    `pulumi:"name"`
}

func (LookupOspfVrfOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOspfVrfArgs)(nil)).Elem()
}

// A collection of values returned by getOspfVrf.
type LookupOspfVrfResultOutput struct{ *pulumi.OutputState }

func (LookupOspfVrfResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOspfVrfResult)(nil)).Elem()
}

func (o LookupOspfVrfResultOutput) ToLookupOspfVrfResultOutput() LookupOspfVrfResultOutput {
	return o
}

func (o LookupOspfVrfResultOutput) ToLookupOspfVrfResultOutputWithContext(ctx context.Context) LookupOspfVrfResultOutput {
	return o
}

func (o LookupOspfVrfResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupOspfVrfResult] {
	return pulumix.Output[LookupOspfVrfResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupOspfVrfResultOutput) AdminState() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfVrfResult) string { return v.AdminState }).(pulumi.StringOutput)
}

func (o LookupOspfVrfResultOutput) BandwidthReference() pulumi.IntOutput {
	return o.ApplyT(func(v LookupOspfVrfResult) int { return v.BandwidthReference }).(pulumi.IntOutput)
}

func (o LookupOspfVrfResultOutput) BanwidthReferenceUnit() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfVrfResult) string { return v.BanwidthReferenceUnit }).(pulumi.StringOutput)
}

func (o LookupOspfVrfResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupOspfVrfResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

func (o LookupOspfVrfResultOutput) Distance() pulumi.IntOutput {
	return o.ApplyT(func(v LookupOspfVrfResult) int { return v.Distance }).(pulumi.IntOutput)
}

func (o LookupOspfVrfResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfVrfResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupOspfVrfResultOutput) InstanceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfVrfResult) string { return v.InstanceName }).(pulumi.StringOutput)
}

func (o LookupOspfVrfResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfVrfResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupOspfVrfResultOutput) RouterId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfVrfResult) string { return v.RouterId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupOspfVrfResultOutput{})
}
