// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Nxos
{
    /// <summary>
    /// This resource can manage the OSPFv3 feature configuration.
    /// 
    /// - API Documentation: [fmOspfv3](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Feature%20Management/fm:Ospfv3/)
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Nxos = Lbrlabs.PulumiPackage.Nxos;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Nxos.FeatureOspfv3("example", new()
    ///     {
    ///         AdminState = "enabled",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    ///  $ pulumi import nxos:index/featureOspfv3:FeatureOspfv3 example "sys/fm/ospfv3"
    /// ```
    /// </summary>
    [NxosResourceType("nxos:index/featureOspfv3:FeatureOspfv3")]
    public partial class FeatureOspfv3 : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Administrative state. - Choices: `enabled`, `disabled`
        /// </summary>
        [Output("adminState")]
        public Output<string> AdminState { get; private set; } = null!;

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Output("device")]
        public Output<string?> Device { get; private set; } = null!;


        /// <summary>
        /// Create a FeatureOspfv3 resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FeatureOspfv3(string name, FeatureOspfv3Args args, CustomResourceOptions? options = null)
            : base("nxos:index/featureOspfv3:FeatureOspfv3", name, args ?? new FeatureOspfv3Args(), MakeResourceOptions(options, ""))
        {
        }

        private FeatureOspfv3(string name, Input<string> id, FeatureOspfv3State? state = null, CustomResourceOptions? options = null)
            : base("nxos:index/featureOspfv3:FeatureOspfv3", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FeatureOspfv3 resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FeatureOspfv3 Get(string name, Input<string> id, FeatureOspfv3State? state = null, CustomResourceOptions? options = null)
        {
            return new FeatureOspfv3(name, id, state, options);
        }
    }

    public sealed class FeatureOspfv3Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Administrative state. - Choices: `enabled`, `disabled`
        /// </summary>
        [Input("adminState", required: true)]
        public Input<string> AdminState { get; set; } = null!;

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        public FeatureOspfv3Args()
        {
        }
        public static new FeatureOspfv3Args Empty => new FeatureOspfv3Args();
    }

    public sealed class FeatureOspfv3State : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Administrative state. - Choices: `enabled`, `disabled`
        /// </summary>
        [Input("adminState")]
        public Input<string>? AdminState { get; set; }

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        public FeatureOspfv3State()
        {
        }
        public static new FeatureOspfv3State Empty => new FeatureOspfv3State();
    }
}
