// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Nxos
{
    public static class GetOspfInstance
    {
        /// <summary>
        /// This data source can read the OSPF instance configuration.
        /// 
        /// - API Documentation: [ospfInst](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Routing%20and%20Forwarding/ospf:Inst/)
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Nxos = Pulumi.Nxos;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Nxos.GetOspfInstance.Invoke(new()
        ///     {
        ///         Name = "OSPF1",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetOspfInstanceResult> InvokeAsync(GetOspfInstanceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetOspfInstanceResult>("nxos:index/getOspfInstance:getOspfInstance", args ?? new GetOspfInstanceArgs(), options.WithDefaults());

        /// <summary>
        /// This data source can read the OSPF instance configuration.
        /// 
        /// - API Documentation: [ospfInst](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Routing%20and%20Forwarding/ospf:Inst/)
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Nxos = Pulumi.Nxos;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Nxos.GetOspfInstance.Invoke(new()
        ///     {
        ///         Name = "OSPF1",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetOspfInstanceResult> Invoke(GetOspfInstanceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetOspfInstanceResult>("nxos:index/getOspfInstance:getOspfInstance", args ?? new GetOspfInstanceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetOspfInstanceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public string? Device { get; set; }

        /// <summary>
        /// OSPF instance name.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetOspfInstanceArgs()
        {
        }
        public static new GetOspfInstanceArgs Empty => new GetOspfInstanceArgs();
    }

    public sealed class GetOspfInstanceInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// OSPF instance name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetOspfInstanceInvokeArgs()
        {
        }
        public static new GetOspfInstanceInvokeArgs Empty => new GetOspfInstanceInvokeArgs();
    }


    [OutputType]
    public sealed class GetOspfInstanceResult
    {
        /// <summary>
        /// Administrative state.
        /// </summary>
        public readonly string AdminState;
        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        public readonly string? Device;
        /// <summary>
        /// The distinguished name of the object.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// OSPF instance name.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetOspfInstanceResult(
            string adminState,

            string? device,

            string id,

            string name)
        {
            AdminState = adminState;
            Device = device;
            Id = id;
            Name = name;
        }
    }
}
