// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.nxos.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetBgpAdvertisedPrefixPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetBgpAdvertisedPrefixPlainArgs Empty = new GetBgpAdvertisedPrefixPlainArgs();

    @Import(name="addressFamily", required=true)
    private String addressFamily;

    public String addressFamily() {
        return this.addressFamily;
    }

    @Import(name="asn", required=true)
    private String asn;

    public String asn() {
        return this.asn;
    }

    @Import(name="device")
    private @Nullable String device;

    public Optional<String> device() {
        return Optional.ofNullable(this.device);
    }

    @Import(name="prefix", required=true)
    private String prefix;

    public String prefix() {
        return this.prefix;
    }

    @Import(name="vrf", required=true)
    private String vrf;

    public String vrf() {
        return this.vrf;
    }

    private GetBgpAdvertisedPrefixPlainArgs() {}

    private GetBgpAdvertisedPrefixPlainArgs(GetBgpAdvertisedPrefixPlainArgs $) {
        this.addressFamily = $.addressFamily;
        this.asn = $.asn;
        this.device = $.device;
        this.prefix = $.prefix;
        this.vrf = $.vrf;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetBgpAdvertisedPrefixPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetBgpAdvertisedPrefixPlainArgs $;

        public Builder() {
            $ = new GetBgpAdvertisedPrefixPlainArgs();
        }

        public Builder(GetBgpAdvertisedPrefixPlainArgs defaults) {
            $ = new GetBgpAdvertisedPrefixPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder addressFamily(String addressFamily) {
            $.addressFamily = addressFamily;
            return this;
        }

        public Builder asn(String asn) {
            $.asn = asn;
            return this;
        }

        public Builder device(@Nullable String device) {
            $.device = device;
            return this;
        }

        public Builder prefix(String prefix) {
            $.prefix = prefix;
            return this;
        }

        public Builder vrf(String vrf) {
            $.vrf = vrf;
            return this;
        }

        public GetBgpAdvertisedPrefixPlainArgs build() {
            $.addressFamily = Objects.requireNonNull($.addressFamily, "expected parameter 'addressFamily' to be non-null");
            $.asn = Objects.requireNonNull($.asn, "expected parameter 'asn' to be non-null");
            $.prefix = Objects.requireNonNull($.prefix, "expected parameter 'prefix' to be non-null");
            $.vrf = Objects.requireNonNull($.vrf, "expected parameter 'vrf' to be non-null");
            return $;
        }
    }

}
