// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.nxos.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetEvpnVniRouteTargetArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetEvpnVniRouteTargetArgs Empty = new GetEvpnVniRouteTargetArgs();

    @Import(name="device")
    private @Nullable Output<String> device;

    public Optional<Output<String>> device() {
        return Optional.ofNullable(this.device);
    }

    @Import(name="direction", required=true)
    private Output<String> direction;

    public Output<String> direction() {
        return this.direction;
    }

    @Import(name="encap", required=true)
    private Output<String> encap;

    public Output<String> encap() {
        return this.encap;
    }

    @Import(name="routeTarget", required=true)
    private Output<String> routeTarget;

    public Output<String> routeTarget() {
        return this.routeTarget;
    }

    private GetEvpnVniRouteTargetArgs() {}

    private GetEvpnVniRouteTargetArgs(GetEvpnVniRouteTargetArgs $) {
        this.device = $.device;
        this.direction = $.direction;
        this.encap = $.encap;
        this.routeTarget = $.routeTarget;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetEvpnVniRouteTargetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetEvpnVniRouteTargetArgs $;

        public Builder() {
            $ = new GetEvpnVniRouteTargetArgs();
        }

        public Builder(GetEvpnVniRouteTargetArgs defaults) {
            $ = new GetEvpnVniRouteTargetArgs(Objects.requireNonNull(defaults));
        }

        public Builder device(@Nullable Output<String> device) {
            $.device = device;
            return this;
        }

        public Builder device(String device) {
            return device(Output.of(device));
        }

        public Builder direction(Output<String> direction) {
            $.direction = direction;
            return this;
        }

        public Builder direction(String direction) {
            return direction(Output.of(direction));
        }

        public Builder encap(Output<String> encap) {
            $.encap = encap;
            return this;
        }

        public Builder encap(String encap) {
            return encap(Output.of(encap));
        }

        public Builder routeTarget(Output<String> routeTarget) {
            $.routeTarget = routeTarget;
            return this;
        }

        public Builder routeTarget(String routeTarget) {
            return routeTarget(Output.of(routeTarget));
        }

        public GetEvpnVniRouteTargetArgs build() {
            $.direction = Objects.requireNonNull($.direction, "expected parameter 'direction' to be non-null");
            $.encap = Objects.requireNonNull($.encap, "expected parameter 'encap' to be non-null");
            $.routeTarget = Objects.requireNonNull($.routeTarget, "expected parameter 'routeTarget' to be non-null");
            return $;
        }
    }

}
