// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.nxos.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNveInterfaceArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNveInterfaceArgs Empty = new GetNveInterfaceArgs();

    @Import(name="device")
    private @Nullable Output<String> device;

    public Optional<Output<String>> device() {
        return Optional.ofNullable(this.device);
    }

    private GetNveInterfaceArgs() {}

    private GetNveInterfaceArgs(GetNveInterfaceArgs $) {
        this.device = $.device;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNveInterfaceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNveInterfaceArgs $;

        public Builder() {
            $ = new GetNveInterfaceArgs();
        }

        public Builder(GetNveInterfaceArgs defaults) {
            $ = new GetNveInterfaceArgs(Objects.requireNonNull(defaults));
        }

        public Builder device(@Nullable Output<String> device) {
            $.device = device;
            return this;
        }

        public Builder device(String device) {
            return device(Output.of(device));
        }

        public GetNveInterfaceArgs build() {
            return $;
        }
    }

}
