// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.nxos.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetRouteMapRuleEntrySetRegularCommunityPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRouteMapRuleEntrySetRegularCommunityPlainArgs Empty = new GetRouteMapRuleEntrySetRegularCommunityPlainArgs();

    @Import(name="device")
    private @Nullable String device;

    public Optional<String> device() {
        return Optional.ofNullable(this.device);
    }

    @Import(name="order", required=true)
    private Integer order;

    public Integer order() {
        return this.order;
    }

    @Import(name="ruleName", required=true)
    private String ruleName;

    public String ruleName() {
        return this.ruleName;
    }

    private GetRouteMapRuleEntrySetRegularCommunityPlainArgs() {}

    private GetRouteMapRuleEntrySetRegularCommunityPlainArgs(GetRouteMapRuleEntrySetRegularCommunityPlainArgs $) {
        this.device = $.device;
        this.order = $.order;
        this.ruleName = $.ruleName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRouteMapRuleEntrySetRegularCommunityPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRouteMapRuleEntrySetRegularCommunityPlainArgs $;

        public Builder() {
            $ = new GetRouteMapRuleEntrySetRegularCommunityPlainArgs();
        }

        public Builder(GetRouteMapRuleEntrySetRegularCommunityPlainArgs defaults) {
            $ = new GetRouteMapRuleEntrySetRegularCommunityPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder device(@Nullable String device) {
            $.device = device;
            return this;
        }

        public Builder order(Integer order) {
            $.order = order;
            return this;
        }

        public Builder ruleName(String ruleName) {
            $.ruleName = ruleName;
            return this;
        }

        public GetRouteMapRuleEntrySetRegularCommunityPlainArgs build() {
            $.order = Objects.requireNonNull($.order, "expected parameter 'order' to be non-null");
            $.ruleName = Objects.requireNonNull($.ruleName, "expected parameter 'ruleName' to be non-null");
            return $;
        }
    }

}
