// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.nxos.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RouteMapRuleEntrySetRegularCommunityItemState extends com.pulumi.resources.ResourceArgs {

    public static final RouteMapRuleEntrySetRegularCommunityItemState Empty = new RouteMapRuleEntrySetRegularCommunityItemState();

    /**
     * Set Community.
     * 
     */
    @Import(name="community")
    private @Nullable Output<String> community;

    /**
     * @return Set Community.
     * 
     */
    public Optional<Output<String>> community() {
        return Optional.ofNullable(this.community);
    }

    /**
     * A device name from the provider configuration.
     * 
     */
    @Import(name="device")
    private @Nullable Output<String> device;

    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Optional<Output<String>> device() {
        return Optional.ofNullable(this.device);
    }

    /**
     * Route-Map Rule Entry order. - Range: `0`-`65535`
     * 
     */
    @Import(name="order")
    private @Nullable Output<Integer> order;

    /**
     * @return Route-Map Rule Entry order. - Range: `0`-`65535`
     * 
     */
    public Optional<Output<Integer>> order() {
        return Optional.ofNullable(this.order);
    }

    /**
     * Route Map rule name.
     * 
     */
    @Import(name="ruleName")
    private @Nullable Output<String> ruleName;

    /**
     * @return Route Map rule name.
     * 
     */
    public Optional<Output<String>> ruleName() {
        return Optional.ofNullable(this.ruleName);
    }

    private RouteMapRuleEntrySetRegularCommunityItemState() {}

    private RouteMapRuleEntrySetRegularCommunityItemState(RouteMapRuleEntrySetRegularCommunityItemState $) {
        this.community = $.community;
        this.device = $.device;
        this.order = $.order;
        this.ruleName = $.ruleName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RouteMapRuleEntrySetRegularCommunityItemState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RouteMapRuleEntrySetRegularCommunityItemState $;

        public Builder() {
            $ = new RouteMapRuleEntrySetRegularCommunityItemState();
        }

        public Builder(RouteMapRuleEntrySetRegularCommunityItemState defaults) {
            $ = new RouteMapRuleEntrySetRegularCommunityItemState(Objects.requireNonNull(defaults));
        }

        /**
         * @param community Set Community.
         * 
         * @return builder
         * 
         */
        public Builder community(@Nullable Output<String> community) {
            $.community = community;
            return this;
        }

        /**
         * @param community Set Community.
         * 
         * @return builder
         * 
         */
        public Builder community(String community) {
            return community(Output.of(community));
        }

        /**
         * @param device A device name from the provider configuration.
         * 
         * @return builder
         * 
         */
        public Builder device(@Nullable Output<String> device) {
            $.device = device;
            return this;
        }

        /**
         * @param device A device name from the provider configuration.
         * 
         * @return builder
         * 
         */
        public Builder device(String device) {
            return device(Output.of(device));
        }

        /**
         * @param order Route-Map Rule Entry order. - Range: `0`-`65535`
         * 
         * @return builder
         * 
         */
        public Builder order(@Nullable Output<Integer> order) {
            $.order = order;
            return this;
        }

        /**
         * @param order Route-Map Rule Entry order. - Range: `0`-`65535`
         * 
         * @return builder
         * 
         */
        public Builder order(Integer order) {
            return order(Output.of(order));
        }

        /**
         * @param ruleName Route Map rule name.
         * 
         * @return builder
         * 
         */
        public Builder ruleName(@Nullable Output<String> ruleName) {
            $.ruleName = ruleName;
            return this;
        }

        /**
         * @param ruleName Route Map rule name.
         * 
         * @return builder
         * 
         */
        public Builder ruleName(String ruleName) {
            return ruleName(Output.of(ruleName));
        }

        public RouteMapRuleEntrySetRegularCommunityItemState build() {
            return $;
        }
    }

}
