// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nxos

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// This data source can read a loopback interface.
//
// - API Documentation: [l3LbRtdIf](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Layer%203/l3:LbRtdIf/)
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := nxos.LookupLoopbackInterface(ctx, &nxos.LookupLoopbackInterfaceArgs{
//				InterfaceId: "lo123",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupLoopbackInterface(ctx *pulumi.Context, args *LookupLoopbackInterfaceArgs, opts ...pulumi.InvokeOption) (*LookupLoopbackInterfaceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupLoopbackInterfaceResult
	err := ctx.Invoke("nxos:index/getLoopbackInterface:getLoopbackInterface", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLoopbackInterface.
type LookupLoopbackInterfaceArgs struct {
	// A device name from the provider configuration.
	Device *string `pulumi:"device"`
	// Must match first field in the output of `show intf brief`. Example: `lo123`.
	InterfaceId string `pulumi:"interfaceId"`
}

// A collection of values returned by getLoopbackInterface.
type LookupLoopbackInterfaceResult struct {
	// Administrative state.
	AdminState string `pulumi:"adminState"`
	// Interface description.
	Description string `pulumi:"description"`
	// A device name from the provider configuration.
	Device *string `pulumi:"device"`
	// The distinguished name of the object.
	Id string `pulumi:"id"`
	// Must match first field in the output of `show intf brief`. Example: `lo123`.
	InterfaceId string `pulumi:"interfaceId"`
}

func LookupLoopbackInterfaceOutput(ctx *pulumi.Context, args LookupLoopbackInterfaceOutputArgs, opts ...pulumi.InvokeOption) LookupLoopbackInterfaceResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupLoopbackInterfaceResult, error) {
			args := v.(LookupLoopbackInterfaceArgs)
			r, err := LookupLoopbackInterface(ctx, &args, opts...)
			var s LookupLoopbackInterfaceResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupLoopbackInterfaceResultOutput)
}

// A collection of arguments for invoking getLoopbackInterface.
type LookupLoopbackInterfaceOutputArgs struct {
	// A device name from the provider configuration.
	Device pulumi.StringPtrInput `pulumi:"device"`
	// Must match first field in the output of `show intf brief`. Example: `lo123`.
	InterfaceId pulumi.StringInput `pulumi:"interfaceId"`
}

func (LookupLoopbackInterfaceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLoopbackInterfaceArgs)(nil)).Elem()
}

// A collection of values returned by getLoopbackInterface.
type LookupLoopbackInterfaceResultOutput struct{ *pulumi.OutputState }

func (LookupLoopbackInterfaceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLoopbackInterfaceResult)(nil)).Elem()
}

func (o LookupLoopbackInterfaceResultOutput) ToLookupLoopbackInterfaceResultOutput() LookupLoopbackInterfaceResultOutput {
	return o
}

func (o LookupLoopbackInterfaceResultOutput) ToLookupLoopbackInterfaceResultOutputWithContext(ctx context.Context) LookupLoopbackInterfaceResultOutput {
	return o
}

func (o LookupLoopbackInterfaceResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupLoopbackInterfaceResult] {
	return pulumix.Output[LookupLoopbackInterfaceResult]{
		OutputState: o.OutputState,
	}
}

// Administrative state.
func (o LookupLoopbackInterfaceResultOutput) AdminState() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoopbackInterfaceResult) string { return v.AdminState }).(pulumi.StringOutput)
}

// Interface description.
func (o LookupLoopbackInterfaceResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoopbackInterfaceResult) string { return v.Description }).(pulumi.StringOutput)
}

// A device name from the provider configuration.
func (o LookupLoopbackInterfaceResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupLoopbackInterfaceResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

// The distinguished name of the object.
func (o LookupLoopbackInterfaceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoopbackInterfaceResult) string { return v.Id }).(pulumi.StringOutput)
}

// Must match first field in the output of `show intf brief`. Example: `lo123`.
func (o LookupLoopbackInterfaceResultOutput) InterfaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoopbackInterfaceResult) string { return v.InterfaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupLoopbackInterfaceResultOutput{})
}
