// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nxos

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// This data source can read the OSPF authentication configuration.
//
// - API Documentation: [ospfAuthNewP](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Routing%20and%20Forwarding/ospf:AuthNewP/)
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := nxos.LookupOspfAuthentication(ctx, &nxos.LookupOspfAuthenticationArgs{
//				InstanceName: "OSPF1",
//				InterfaceId:  "eth1/10",
//				VrfName:      "VRF1",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupOspfAuthentication(ctx *pulumi.Context, args *LookupOspfAuthenticationArgs, opts ...pulumi.InvokeOption) (*LookupOspfAuthenticationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupOspfAuthenticationResult
	err := ctx.Invoke("nxos:index/getOspfAuthentication:getOspfAuthentication", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOspfAuthentication.
type LookupOspfAuthenticationArgs struct {
	// A device name from the provider configuration.
	Device *string `pulumi:"device"`
	// OSPF instance name.
	InstanceName string `pulumi:"instanceName"`
	// Must match first field in the output of `show intf brief`. Example: `eth1/1`.
	InterfaceId string `pulumi:"interfaceId"`
	// VRF name.
	VrfName string `pulumi:"vrfName"`
}

// A collection of values returned by getOspfAuthentication.
type LookupOspfAuthenticationResult struct {
	// A device name from the provider configuration.
	Device *string `pulumi:"device"`
	// The distinguished name of the object.
	Id string `pulumi:"id"`
	// OSPF instance name.
	InstanceName string `pulumi:"instanceName"`
	// Must match first field in the output of `show intf brief`. Example: `eth1/1`.
	InterfaceId string `pulumi:"interfaceId"`
	// Key used for authentication.
	Key string `pulumi:"key"`
	// Key ID used for authentication.
	KeyId int `pulumi:"keyId"`
	// Encrypted authentication key or plain text key.
	KeySecureMode bool `pulumi:"keySecureMode"`
	// Authentication keychain.
	Keychain string `pulumi:"keychain"`
	// Key used for md5 authentication.
	Md5Key string `pulumi:"md5Key"`
	// Encrypted authentication md5 key or plain text key.
	Md5KeySecureMode bool `pulumi:"md5KeySecureMode"`
	// Authentication type.
	Type string `pulumi:"type"`
	// VRF name.
	VrfName string `pulumi:"vrfName"`
}

func LookupOspfAuthenticationOutput(ctx *pulumi.Context, args LookupOspfAuthenticationOutputArgs, opts ...pulumi.InvokeOption) LookupOspfAuthenticationResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupOspfAuthenticationResult, error) {
			args := v.(LookupOspfAuthenticationArgs)
			r, err := LookupOspfAuthentication(ctx, &args, opts...)
			var s LookupOspfAuthenticationResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupOspfAuthenticationResultOutput)
}

// A collection of arguments for invoking getOspfAuthentication.
type LookupOspfAuthenticationOutputArgs struct {
	// A device name from the provider configuration.
	Device pulumi.StringPtrInput `pulumi:"device"`
	// OSPF instance name.
	InstanceName pulumi.StringInput `pulumi:"instanceName"`
	// Must match first field in the output of `show intf brief`. Example: `eth1/1`.
	InterfaceId pulumi.StringInput `pulumi:"interfaceId"`
	// VRF name.
	VrfName pulumi.StringInput `pulumi:"vrfName"`
}

func (LookupOspfAuthenticationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOspfAuthenticationArgs)(nil)).Elem()
}

// A collection of values returned by getOspfAuthentication.
type LookupOspfAuthenticationResultOutput struct{ *pulumi.OutputState }

func (LookupOspfAuthenticationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOspfAuthenticationResult)(nil)).Elem()
}

func (o LookupOspfAuthenticationResultOutput) ToLookupOspfAuthenticationResultOutput() LookupOspfAuthenticationResultOutput {
	return o
}

func (o LookupOspfAuthenticationResultOutput) ToLookupOspfAuthenticationResultOutputWithContext(ctx context.Context) LookupOspfAuthenticationResultOutput {
	return o
}

func (o LookupOspfAuthenticationResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupOspfAuthenticationResult] {
	return pulumix.Output[LookupOspfAuthenticationResult]{
		OutputState: o.OutputState,
	}
}

// A device name from the provider configuration.
func (o LookupOspfAuthenticationResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

// The distinguished name of the object.
func (o LookupOspfAuthenticationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) string { return v.Id }).(pulumi.StringOutput)
}

// OSPF instance name.
func (o LookupOspfAuthenticationResultOutput) InstanceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) string { return v.InstanceName }).(pulumi.StringOutput)
}

// Must match first field in the output of `show intf brief`. Example: `eth1/1`.
func (o LookupOspfAuthenticationResultOutput) InterfaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) string { return v.InterfaceId }).(pulumi.StringOutput)
}

// Key used for authentication.
func (o LookupOspfAuthenticationResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) string { return v.Key }).(pulumi.StringOutput)
}

// Key ID used for authentication.
func (o LookupOspfAuthenticationResultOutput) KeyId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) int { return v.KeyId }).(pulumi.IntOutput)
}

// Encrypted authentication key or plain text key.
func (o LookupOspfAuthenticationResultOutput) KeySecureMode() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) bool { return v.KeySecureMode }).(pulumi.BoolOutput)
}

// Authentication keychain.
func (o LookupOspfAuthenticationResultOutput) Keychain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) string { return v.Keychain }).(pulumi.StringOutput)
}

// Key used for md5 authentication.
func (o LookupOspfAuthenticationResultOutput) Md5Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) string { return v.Md5Key }).(pulumi.StringOutput)
}

// Encrypted authentication md5 key or plain text key.
func (o LookupOspfAuthenticationResultOutput) Md5KeySecureMode() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) bool { return v.Md5KeySecureMode }).(pulumi.BoolOutput)
}

// Authentication type.
func (o LookupOspfAuthenticationResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) string { return v.Type }).(pulumi.StringOutput)
}

// VRF name.
func (o LookupOspfAuthenticationResultOutput) VrfName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOspfAuthenticationResult) string { return v.VrfName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupOspfAuthenticationResultOutput{})
}
