// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nxos

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// This data source can read the queuing QoS policy system out configuration.
//
// - API Documentation: [ipqosSystem](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Qos/ipqos:System/)
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lbrlabs/pulumi-nxos/sdk/go/nxos"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := nxos.LookupQueuingQosPolicySystemOut(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupQueuingQosPolicySystemOut(ctx *pulumi.Context, args *LookupQueuingQosPolicySystemOutArgs, opts ...pulumi.InvokeOption) (*LookupQueuingQosPolicySystemOutResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupQueuingQosPolicySystemOutResult
	err := ctx.Invoke("nxos:index/getQueuingQosPolicySystemOut:getQueuingQosPolicySystemOut", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getQueuingQosPolicySystemOut.
type LookupQueuingQosPolicySystemOutArgs struct {
	// A device name from the provider configuration.
	Device *string `pulumi:"device"`
}

// A collection of values returned by getQueuingQosPolicySystemOut.
type LookupQueuingQosPolicySystemOutResult struct {
	// A device name from the provider configuration.
	Device *string `pulumi:"device"`
	// The distinguished name of the object.
	Id string `pulumi:"id"`
}

func LookupQueuingQosPolicySystemOutOutput(ctx *pulumi.Context, args LookupQueuingQosPolicySystemOutOutputArgs, opts ...pulumi.InvokeOption) LookupQueuingQosPolicySystemOutResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupQueuingQosPolicySystemOutResult, error) {
			args := v.(LookupQueuingQosPolicySystemOutArgs)
			r, err := LookupQueuingQosPolicySystemOut(ctx, &args, opts...)
			var s LookupQueuingQosPolicySystemOutResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupQueuingQosPolicySystemOutResultOutput)
}

// A collection of arguments for invoking getQueuingQosPolicySystemOut.
type LookupQueuingQosPolicySystemOutOutputArgs struct {
	// A device name from the provider configuration.
	Device pulumi.StringPtrInput `pulumi:"device"`
}

func (LookupQueuingQosPolicySystemOutOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupQueuingQosPolicySystemOutArgs)(nil)).Elem()
}

// A collection of values returned by getQueuingQosPolicySystemOut.
type LookupQueuingQosPolicySystemOutResultOutput struct{ *pulumi.OutputState }

func (LookupQueuingQosPolicySystemOutResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupQueuingQosPolicySystemOutResult)(nil)).Elem()
}

func (o LookupQueuingQosPolicySystemOutResultOutput) ToLookupQueuingQosPolicySystemOutResultOutput() LookupQueuingQosPolicySystemOutResultOutput {
	return o
}

func (o LookupQueuingQosPolicySystemOutResultOutput) ToLookupQueuingQosPolicySystemOutResultOutputWithContext(ctx context.Context) LookupQueuingQosPolicySystemOutResultOutput {
	return o
}

func (o LookupQueuingQosPolicySystemOutResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupQueuingQosPolicySystemOutResult] {
	return pulumix.Output[LookupQueuingQosPolicySystemOutResult]{
		OutputState: o.OutputState,
	}
}

// A device name from the provider configuration.
func (o LookupQueuingQosPolicySystemOutResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupQueuingQosPolicySystemOutResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

// The distinguished name of the object.
func (o LookupQueuingQosPolicySystemOutResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQueuingQosPolicySystemOutResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupQueuingQosPolicySystemOutResultOutput{})
}
