// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetIpv4AccessListEntryArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetIpv4AccessListEntryArgs Empty = new GetIpv4AccessListEntryArgs();

    /**
     * A device name from the provider configuration.
     * 
     */
    @Import(name="device")
    private @Nullable Output<String> device;

    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Optional<Output<String>> device() {
        return Optional.ofNullable(this.device);
    }

    /**
     * Access list name.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Access list name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Sequence number.
     * 
     */
    @Import(name="sequenceNumber", required=true)
    private Output<Integer> sequenceNumber;

    /**
     * @return Sequence number.
     * 
     */
    public Output<Integer> sequenceNumber() {
        return this.sequenceNumber;
    }

    private GetIpv4AccessListEntryArgs() {}

    private GetIpv4AccessListEntryArgs(GetIpv4AccessListEntryArgs $) {
        this.device = $.device;
        this.name = $.name;
        this.sequenceNumber = $.sequenceNumber;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetIpv4AccessListEntryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetIpv4AccessListEntryArgs $;

        public Builder() {
            $ = new GetIpv4AccessListEntryArgs();
        }

        public Builder(GetIpv4AccessListEntryArgs defaults) {
            $ = new GetIpv4AccessListEntryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param device A device name from the provider configuration.
         * 
         * @return builder
         * 
         */
        public Builder device(@Nullable Output<String> device) {
            $.device = device;
            return this;
        }

        /**
         * @param device A device name from the provider configuration.
         * 
         * @return builder
         * 
         */
        public Builder device(String device) {
            return device(Output.of(device));
        }

        /**
         * @param name Access list name.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Access list name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param sequenceNumber Sequence number.
         * 
         * @return builder
         * 
         */
        public Builder sequenceNumber(Output<Integer> sequenceNumber) {
            $.sequenceNumber = sequenceNumber;
            return this;
        }

        /**
         * @param sequenceNumber Sequence number.
         * 
         * @return builder
         * 
         */
        public Builder sequenceNumber(Integer sequenceNumber) {
            return sequenceNumber(Output.of(sequenceNumber));
        }

        public GetIpv4AccessListEntryArgs build() {
            $.name = Objects.requireNonNull($.name, "expected parameter 'name' to be non-null");
            $.sequenceNumber = Objects.requireNonNull($.sequenceNumber, "expected parameter 'sequenceNumber' to be non-null");
            return $;
        }
    }

}
