// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetRouteMapRuleEntrySetRegularCommunityResult {
    /**
     * @return Option to add to an existing community.
     * 
     */
    private String additive;
    /**
     * @return A device name from the provider configuration.
     * 
     */
    private @Nullable String device;
    /**
     * @return The distinguished name of the object.
     * 
     */
    private String id;
    /**
     * @return Option to have no community attribute.
     * 
     */
    private String noCommunity;
    /**
     * @return Route-Map Rule Entry order.
     * 
     */
    private Integer order;
    /**
     * @return Route Map rule name.
     * 
     */
    private String ruleName;
    /**
     * @return Operation on the current community.
     * 
     */
    private String setCriteria;

    private GetRouteMapRuleEntrySetRegularCommunityResult() {}
    /**
     * @return Option to add to an existing community.
     * 
     */
    public String additive() {
        return this.additive;
    }
    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Optional<String> device() {
        return Optional.ofNullable(this.device);
    }
    /**
     * @return The distinguished name of the object.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Option to have no community attribute.
     * 
     */
    public String noCommunity() {
        return this.noCommunity;
    }
    /**
     * @return Route-Map Rule Entry order.
     * 
     */
    public Integer order() {
        return this.order;
    }
    /**
     * @return Route Map rule name.
     * 
     */
    public String ruleName() {
        return this.ruleName;
    }
    /**
     * @return Operation on the current community.
     * 
     */
    public String setCriteria() {
        return this.setCriteria;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRouteMapRuleEntrySetRegularCommunityResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String additive;
        private @Nullable String device;
        private String id;
        private String noCommunity;
        private Integer order;
        private String ruleName;
        private String setCriteria;
        public Builder() {}
        public Builder(GetRouteMapRuleEntrySetRegularCommunityResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.additive = defaults.additive;
    	      this.device = defaults.device;
    	      this.id = defaults.id;
    	      this.noCommunity = defaults.noCommunity;
    	      this.order = defaults.order;
    	      this.ruleName = defaults.ruleName;
    	      this.setCriteria = defaults.setCriteria;
        }

        @CustomType.Setter
        public Builder additive(String additive) {
            this.additive = Objects.requireNonNull(additive);
            return this;
        }
        @CustomType.Setter
        public Builder device(@Nullable String device) {
            this.device = device;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder noCommunity(String noCommunity) {
            this.noCommunity = Objects.requireNonNull(noCommunity);
            return this;
        }
        @CustomType.Setter
        public Builder order(Integer order) {
            this.order = Objects.requireNonNull(order);
            return this;
        }
        @CustomType.Setter
        public Builder ruleName(String ruleName) {
            this.ruleName = Objects.requireNonNull(ruleName);
            return this;
        }
        @CustomType.Setter
        public Builder setCriteria(String setCriteria) {
            this.setCriteria = Objects.requireNonNull(setCriteria);
            return this;
        }
        public GetRouteMapRuleEntrySetRegularCommunityResult build() {
            final var o = new GetRouteMapRuleEntrySetRegularCommunityResult();
            o.additive = additive;
            o.device = device;
            o.id = id;
            o.noCommunity = noCommunity;
            o.order = order;
            o.ruleName = ruleName;
            o.setCriteria = setCriteria;
            return o;
        }
    }
}
