// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.nxos.BridgeDomainArgs;
import com.pulumi.nxos.Utilities;
import com.pulumi.nxos.inputs.BridgeDomainState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage a bridge domain.
 * 
 * - API Documentation: [l2BD](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Layer%202/l2:BD/)
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.nxos.BridgeDomain;
 * import com.pulumi.nxos.BridgeDomainArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new BridgeDomain(&#34;example&#34;, BridgeDomainArgs.builder()        
 *             .accessEncap(&#34;unknown&#34;)
 *             .fabricEncap(&#34;vlan-10&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * ```sh
 *  $ pulumi import nxos:index/bridgeDomain:BridgeDomain example &#34;sys/bd/bd-[vlan-10]&#34;
 * ```
 * 
 */
@ResourceType(type="nxos:index/bridgeDomain:BridgeDomain")
public class BridgeDomain extends com.pulumi.resources.CustomResource {
    /**
     * Access encapsulation. Possible values are `unknown`, `vlan-XX` or `vxlan-XX`. - Default value: `unknown`
     * 
     */
    @Export(name="accessEncap", refs={String.class}, tree="[0]")
    private Output<String> accessEncap;

    /**
     * @return Access encapsulation. Possible values are `unknown`, `vlan-XX` or `vxlan-XX`. - Default value: `unknown`
     * 
     */
    public Output<String> accessEncap() {
        return this.accessEncap;
    }
    /**
     * A device name from the provider configuration.
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    /**
     * Fabric encapsulation. Possible values are `unknown`, `vlan-XX` or `vxlan-XX`. - Default value: `unknown`
     * 
     */
    @Export(name="fabricEncap", refs={String.class}, tree="[0]")
    private Output<String> fabricEncap;

    /**
     * @return Fabric encapsulation. Possible values are `unknown`, `vlan-XX` or `vxlan-XX`. - Default value: `unknown`
     * 
     */
    public Output<String> fabricEncap() {
        return this.fabricEncap;
    }
    /**
     * Bridge domain name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Bridge domain name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public BridgeDomain(String name) {
        this(name, BridgeDomainArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public BridgeDomain(String name, BridgeDomainArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public BridgeDomain(String name, BridgeDomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/bridgeDomain:BridgeDomain", name, args == null ? BridgeDomainArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private BridgeDomain(String name, Output<String> id, @Nullable BridgeDomainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/bridgeDomain:BridgeDomain", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static BridgeDomain get(String name, Output<String> id, @Nullable BridgeDomainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new BridgeDomain(name, id, state, options);
    }
}
