// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.nxos.DhcpRelayInterfaceArgs;
import com.pulumi.nxos.Utilities;
import com.pulumi.nxos.inputs.DhcpRelayInterfaceState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage a DHCP relay interface.
 * 
 * - API Documentation: [dhcpRelayIf](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/DHCP/dhcp:RelayIf/)
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.nxos.DhcpRelayInterface;
 * import com.pulumi.nxos.DhcpRelayInterfaceArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new DhcpRelayInterface(&#34;example&#34;, DhcpRelayInterfaceArgs.builder()        
 *             .interfaceId(&#34;eth1/10&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * ```sh
 *  $ pulumi import nxos:index/dhcpRelayInterface:DhcpRelayInterface example &#34;sys/dhcp/inst/relayif-[eth1/10]&#34;
 * ```
 * 
 */
@ResourceType(type="nxos:index/dhcpRelayInterface:DhcpRelayInterface")
public class DhcpRelayInterface extends com.pulumi.resources.CustomResource {
    /**
     * A device name from the provider configuration.
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    /**
     * Must match first field in the output of `show intf brief`. Example: `eth1/1`.
     * 
     */
    @Export(name="interfaceId", refs={String.class}, tree="[0]")
    private Output<String> interfaceId;

    /**
     * @return Must match first field in the output of `show intf brief`. Example: `eth1/1`.
     * 
     */
    public Output<String> interfaceId() {
        return this.interfaceId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DhcpRelayInterface(String name) {
        this(name, DhcpRelayInterfaceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DhcpRelayInterface(String name, DhcpRelayInterfaceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DhcpRelayInterface(String name, DhcpRelayInterfaceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/dhcpRelayInterface:DhcpRelayInterface", name, args == null ? DhcpRelayInterfaceArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private DhcpRelayInterface(String name, Output<String> id, @Nullable DhcpRelayInterfaceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/dhcpRelayInterface:DhcpRelayInterface", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DhcpRelayInterface get(String name, Output<String> id, @Nullable DhcpRelayInterfaceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DhcpRelayInterface(name, id, state, options);
    }
}
