// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.nxos.HmmInterfaceArgs;
import com.pulumi.nxos.Utilities;
import com.pulumi.nxos.inputs.HmmInterfaceState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage the HMM Fabric Forwarding mode information related to an Interface.
 * 
 * - API Documentation: [hmmFwdIf](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Host%20Mobility/hmm:FwdIf/)
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.nxos.HmmInterface;
 * import com.pulumi.nxos.HmmInterfaceArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new HmmInterface(&#34;example&#34;, HmmInterfaceArgs.builder()        
 *             .adminState(&#34;enabled&#34;)
 *             .interfaceId(&#34;vlan10&#34;)
 *             .mode(&#34;anycastGW&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * ```sh
 *  $ pulumi import nxos:index/hmmInterface:HmmInterface example &#34;sys/hmm/fwdinst/if-[vlan10]&#34;
 * ```
 * 
 */
@ResourceType(type="nxos:index/hmmInterface:HmmInterface")
public class HmmInterface extends com.pulumi.resources.CustomResource {
    /**
     * Administrative state. - Choices: `enabled`, `disabled` - Default value: `enabled`
     * 
     */
    @Export(name="adminState", refs={String.class}, tree="[0]")
    private Output<String> adminState;

    /**
     * @return Administrative state. - Choices: `enabled`, `disabled` - Default value: `enabled`
     * 
     */
    public Output<String> adminState() {
        return this.adminState;
    }
    /**
     * A device name from the provider configuration.
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    /**
     * Must match first field in the output of `show intf brief`. Example: `vlan10`.
     * 
     */
    @Export(name="interfaceId", refs={String.class}, tree="[0]")
    private Output<String> interfaceId;

    /**
     * @return Must match first field in the output of `show intf brief`. Example: `vlan10`.
     * 
     */
    public Output<String> interfaceId() {
        return this.interfaceId;
    }
    /**
     * HMM Fabric Forwarding mode information for the interface. - Choices: `standard`, `anycastGW`, `proxyGW` - Default value:
     * `standard`
     * 
     */
    @Export(name="mode", refs={String.class}, tree="[0]")
    private Output<String> mode;

    /**
     * @return HMM Fabric Forwarding mode information for the interface. - Choices: `standard`, `anycastGW`, `proxyGW` - Default value:
     * `standard`
     * 
     */
    public Output<String> mode() {
        return this.mode;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public HmmInterface(String name) {
        this(name, HmmInterfaceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public HmmInterface(String name, HmmInterfaceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public HmmInterface(String name, HmmInterfaceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/hmmInterface:HmmInterface", name, args == null ? HmmInterfaceArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private HmmInterface(String name, Output<String> id, @Nullable HmmInterfaceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/hmmInterface:HmmInterface", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static HmmInterface get(String name, Output<String> id, @Nullable HmmInterfaceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new HmmInterface(name, id, state, options);
    }
}
