// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.nxos.NtpServerArgs;
import com.pulumi.nxos.Utilities;
import com.pulumi.nxos.inputs.NtpServerState;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage an ntp server or peer.
 * 
 * - API Documentation: [datetimeNtpProvider](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/System/datetime:NtpProvider/)
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.nxos.NtpServer;
 * import com.pulumi.nxos.NtpServerArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new NtpServer(&#34;example&#34;, NtpServerArgs.builder()        
 *             .keyId(10)
 *             .maxPoll(6)
 *             .minPoll(4)
 *             .type(&#34;server&#34;)
 *             .vrf(&#34;management&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * ```sh
 *  $ pulumi import nxos:index/ntpServer:NtpServer example &#34;sys/time/prov-[1.2.3.4]&#34;
 * ```
 * 
 */
@ResourceType(type="nxos:index/ntpServer:NtpServer")
public class NtpServer extends com.pulumi.resources.CustomResource {
    /**
     * A device name from the provider configuration.
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    /**
     * NTP provider key ID. Possible range is from `1` to `65535`. - Range: `1`-`65535`
     * 
     */
    @Export(name="keyId", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> keyId;

    /**
     * @return NTP provider key ID. Possible range is from `1` to `65535`. - Range: `1`-`65535`
     * 
     */
    public Output<Optional<Integer>> keyId() {
        return Codegen.optional(this.keyId);
    }
    /**
     * NTP maximum interval default in seconds. Possible range is from `4` to `16`. - Range: `4`-`16` - Default value: `6`
     * 
     */
    @Export(name="maxPoll", refs={Integer.class}, tree="[0]")
    private Output<Integer> maxPoll;

    /**
     * @return NTP maximum interval default in seconds. Possible range is from `4` to `16`. - Range: `4`-`16` - Default value: `6`
     * 
     */
    public Output<Integer> maxPoll() {
        return this.maxPoll;
    }
    /**
     * NTP minimum interval default in seconds. Possible range is from `4` to `16`. - Range: `4`-`16` - Default value: `4`
     * 
     */
    @Export(name="minPoll", refs={Integer.class}, tree="[0]")
    private Output<Integer> minPoll;

    /**
     * @return NTP minimum interval default in seconds. Possible range is from `4` to `16`. - Range: `4`-`16` - Default value: `4`
     * 
     */
    public Output<Integer> minPoll() {
        return this.minPoll;
    }
    /**
     * NTP server.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return NTP server.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * NTP provider type. Possible values are `server` or `peer`. - Choices: `server`, `peer`
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return NTP provider type. Possible values are `server` or `peer`. - Choices: `server`, `peer`
     * 
     */
    public Output<String> type() {
        return this.type;
    }
    /**
     * Identifies the VRF for the NTP providers. - Default value: `default`
     * 
     */
    @Export(name="vrf", refs={String.class}, tree="[0]")
    private Output<String> vrf;

    /**
     * @return Identifies the VRF for the NTP providers. - Default value: `default`
     * 
     */
    public Output<String> vrf() {
        return this.vrf;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NtpServer(String name) {
        this(name, NtpServerArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NtpServer(String name, NtpServerArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NtpServer(String name, NtpServerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/ntpServer:NtpServer", name, args == null ? NtpServerArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private NtpServer(String name, Output<String> id, @Nullable NtpServerState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/ntpServer:NtpServer", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NtpServer get(String name, Output<String> id, @Nullable NtpServerState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NtpServer(name, id, state, options);
    }
}
