// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.nxos.OspfVrfArgs;
import com.pulumi.nxos.Utilities;
import com.pulumi.nxos.inputs.OspfVrfState;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage the OSPF VRF configuration.
 * 
 * - API Documentation: [ospfDom](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Routing%20and%20Forwarding/ospf:Dom/)
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.nxos.OspfVrf;
 * import com.pulumi.nxos.OspfVrfArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new OspfVrf(&#34;example&#34;, OspfVrfArgs.builder()        
 *             .adminState(&#34;enabled&#34;)
 *             .bandwidthReference(400000)
 *             .banwidthReferenceUnit(&#34;mbps&#34;)
 *             .distance(110)
 *             .instanceName(&#34;OSPF1&#34;)
 *             .routerId(&#34;34.56.78.90&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * ```sh
 *  $ pulumi import nxos:index/ospfVrf:OspfVrf example &#34;sys/ospf/inst-[OSPF1]/dom-[VRF1]&#34;
 * ```
 * 
 */
@ResourceType(type="nxos:index/ospfVrf:OspfVrf")
public class OspfVrf extends com.pulumi.resources.CustomResource {
    /**
     * Administrative state. - Choices: `enabled`, `disabled` - Default value: `enabled`
     * 
     */
    @Export(name="adminState", refs={String.class}, tree="[0]")
    private Output<String> adminState;

    /**
     * @return Administrative state. - Choices: `enabled`, `disabled` - Default value: `enabled`
     * 
     */
    public Output<String> adminState() {
        return this.adminState;
    }
    /**
     * Bandwidth reference value. - Range: `0`-`4294967295` - Default value: `40000`
     * 
     */
    @Export(name="bandwidthReference", refs={Integer.class}, tree="[0]")
    private Output<Integer> bandwidthReference;

    /**
     * @return Bandwidth reference value. - Range: `0`-`4294967295` - Default value: `40000`
     * 
     */
    public Output<Integer> bandwidthReference() {
        return this.bandwidthReference;
    }
    /**
     * Bandwidth reference unit. - Choices: `mbps`, `gbps` - Default value: `mbps`
     * 
     */
    @Export(name="banwidthReferenceUnit", refs={String.class}, tree="[0]")
    private Output<String> banwidthReferenceUnit;

    /**
     * @return Bandwidth reference unit. - Choices: `mbps`, `gbps` - Default value: `mbps`
     * 
     */
    public Output<String> banwidthReferenceUnit() {
        return this.banwidthReferenceUnit;
    }
    /**
     * A device name from the provider configuration.
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    /**
     * Administrative distance preference. - Range: `1`-`255` - Default value: `110`
     * 
     */
    @Export(name="distance", refs={Integer.class}, tree="[0]")
    private Output<Integer> distance;

    /**
     * @return Administrative distance preference. - Range: `1`-`255` - Default value: `110`
     * 
     */
    public Output<Integer> distance() {
        return this.distance;
    }
    /**
     * OSPF instance name.
     * 
     */
    @Export(name="instanceName", refs={String.class}, tree="[0]")
    private Output<String> instanceName;

    /**
     * @return OSPF instance name.
     * 
     */
    public Output<String> instanceName() {
        return this.instanceName;
    }
    /**
     * VRF name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return VRF name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Router ID. - Default value: `0.0.0.0`
     * 
     */
    @Export(name="routerId", refs={String.class}, tree="[0]")
    private Output<String> routerId;

    /**
     * @return Router ID. - Default value: `0.0.0.0`
     * 
     */
    public Output<String> routerId() {
        return this.routerId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public OspfVrf(String name) {
        this(name, OspfVrfArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public OspfVrf(String name, OspfVrfArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public OspfVrf(String name, OspfVrfArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/ospfVrf:OspfVrf", name, args == null ? OspfVrfArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private OspfVrf(String name, Output<String> id, @Nullable OspfVrfState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/ospfVrf:OspfVrf", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static OspfVrf get(String name, Output<String> id, @Nullable OspfVrfState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new OspfVrf(name, id, state, options);
    }
}
