// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.nxos.QueuingQosPolicyMapMatchClassMapArgs;
import com.pulumi.nxos.Utilities;
import com.pulumi.nxos.inputs.QueuingQosPolicyMapMatchClassMapState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage the queuing QoS policy map match class map configuration.
 * 
 * - API Documentation: [ipqosMatchCMap](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Qos/ipqos:MatchCMap/)
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.nxos.QueuingQosPolicyMapMatchClassMap;
 * import com.pulumi.nxos.QueuingQosPolicyMapMatchClassMapArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new QueuingQosPolicyMapMatchClassMap(&#34;example&#34;, QueuingQosPolicyMapMatchClassMapArgs.builder()        
 *             .policyMapName(&#34;PM1&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * ```sh
 *  $ pulumi import nxos:index/queuingQosPolicyMapMatchClassMap:QueuingQosPolicyMapMatchClassMap example &#34;sys/ipqos/queuing/p/name-[PM1]/cmap-[c-out-q1]&#34;
 * ```
 * 
 */
@ResourceType(type="nxos:index/queuingQosPolicyMapMatchClassMap:QueuingQosPolicyMapMatchClassMap")
public class QueuingQosPolicyMapMatchClassMap extends com.pulumi.resources.CustomResource {
    /**
     * A device name from the provider configuration.
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    /**
     * Class map name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Class map name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Policy map name.
     * 
     */
    @Export(name="policyMapName", refs={String.class}, tree="[0]")
    private Output<String> policyMapName;

    /**
     * @return Policy map name.
     * 
     */
    public Output<String> policyMapName() {
        return this.policyMapName;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public QueuingQosPolicyMapMatchClassMap(String name) {
        this(name, QueuingQosPolicyMapMatchClassMapArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public QueuingQosPolicyMapMatchClassMap(String name, QueuingQosPolicyMapMatchClassMapArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public QueuingQosPolicyMapMatchClassMap(String name, QueuingQosPolicyMapMatchClassMapArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/queuingQosPolicyMapMatchClassMap:QueuingQosPolicyMapMatchClassMap", name, args == null ? QueuingQosPolicyMapMatchClassMapArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private QueuingQosPolicyMapMatchClassMap(String name, Output<String> id, @Nullable QueuingQosPolicyMapMatchClassMapState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nxos:index/queuingQosPolicyMapMatchClassMap:QueuingQosPolicyMapMatchClassMap", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static QueuingQosPolicyMapMatchClassMap get(String name, Output<String> id, @Nullable QueuingQosPolicyMapMatchClassMapState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new QueuingQosPolicyMapMatchClassMap(name, id, state, options);
    }
}
