// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Nxos.Nxos
{
    [NxosResourceType("nxos:nxos/bridgeDomain:BridgeDomain")]
    public partial class BridgeDomain : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Access encapsulation. Possible values are `unknown`, `vlan-XX` or `vxlan-XX`. - Default value: `unknown`
        /// </summary>
        [Output("accessEncap")]
        public Output<string> AccessEncap { get; private set; } = null!;

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Output("device")]
        public Output<string?> Device { get; private set; } = null!;

        /// <summary>
        /// Fabric encapsulation. Possible values are `unknown`, `vlan-XX` or `vxlan-XX`. - Default value: `unknown`
        /// </summary>
        [Output("fabricEncap")]
        public Output<string> FabricEncap { get; private set; } = null!;

        /// <summary>
        /// Bridge domain name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a BridgeDomain resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public BridgeDomain(string name, BridgeDomainArgs args, CustomResourceOptions? options = null)
            : base("nxos:nxos/bridgeDomain:BridgeDomain", name, args ?? new BridgeDomainArgs(), MakeResourceOptions(options, ""))
        {
        }

        private BridgeDomain(string name, Input<string> id, BridgeDomainState? state = null, CustomResourceOptions? options = null)
            : base("nxos:nxos/bridgeDomain:BridgeDomain", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing BridgeDomain resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static BridgeDomain Get(string name, Input<string> id, BridgeDomainState? state = null, CustomResourceOptions? options = null)
        {
            return new BridgeDomain(name, id, state, options);
        }
    }

    public sealed class BridgeDomainArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access encapsulation. Possible values are `unknown`, `vlan-XX` or `vxlan-XX`. - Default value: `unknown`
        /// </summary>
        [Input("accessEncap")]
        public Input<string>? AccessEncap { get; set; }

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// Fabric encapsulation. Possible values are `unknown`, `vlan-XX` or `vxlan-XX`. - Default value: `unknown`
        /// </summary>
        [Input("fabricEncap", required: true)]
        public Input<string> FabricEncap { get; set; } = null!;

        /// <summary>
        /// Bridge domain name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public BridgeDomainArgs()
        {
        }
        public static new BridgeDomainArgs Empty => new BridgeDomainArgs();
    }

    public sealed class BridgeDomainState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access encapsulation. Possible values are `unknown`, `vlan-XX` or `vxlan-XX`. - Default value: `unknown`
        /// </summary>
        [Input("accessEncap")]
        public Input<string>? AccessEncap { get; set; }

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// Fabric encapsulation. Possible values are `unknown`, `vlan-XX` or `vxlan-XX`. - Default value: `unknown`
        /// </summary>
        [Input("fabricEncap")]
        public Input<string>? FabricEncap { get; set; }

        /// <summary>
        /// Bridge domain name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public BridgeDomainState()
        {
        }
        public static new BridgeDomainState Empty => new BridgeDomainState();
    }
}
