// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Nxos.Nxos
{
    public static class GetHmm
    {
        public static Task<GetHmmResult> InvokeAsync(GetHmmArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetHmmResult>("nxos:nxos/getHmm:getHmm", args ?? new GetHmmArgs(), options.WithDefaults());

        public static Output<GetHmmResult> Invoke(GetHmmInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetHmmResult>("nxos:nxos/getHmm:getHmm", args ?? new GetHmmInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetHmmArgs : global::Pulumi.InvokeArgs
    {
        [Input("device")]
        public string? Device { get; set; }

        public GetHmmArgs()
        {
        }
        public static new GetHmmArgs Empty => new GetHmmArgs();
    }

    public sealed class GetHmmInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("device")]
        public Input<string>? Device { get; set; }

        public GetHmmInvokeArgs()
        {
        }
        public static new GetHmmInvokeArgs Empty => new GetHmmInvokeArgs();
    }


    [OutputType]
    public sealed class GetHmmResult
    {
        public readonly string AdminState;
        public readonly string? Device;
        public readonly string Id;

        [OutputConstructor]
        private GetHmmResult(
            string adminState,

            string? device,

            string id)
        {
            AdminState = adminState;
            Device = device;
            Id = id;
        }
    }
}
