// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Nxos.Nxos
{
    public static class GetIpv4AccessListPolicyIngressInterface
    {
        public static Task<GetIpv4AccessListPolicyIngressInterfaceResult> InvokeAsync(GetIpv4AccessListPolicyIngressInterfaceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetIpv4AccessListPolicyIngressInterfaceResult>("nxos:nxos/getIpv4AccessListPolicyIngressInterface:getIpv4AccessListPolicyIngressInterface", args ?? new GetIpv4AccessListPolicyIngressInterfaceArgs(), options.WithDefaults());

        public static Output<GetIpv4AccessListPolicyIngressInterfaceResult> Invoke(GetIpv4AccessListPolicyIngressInterfaceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetIpv4AccessListPolicyIngressInterfaceResult>("nxos:nxos/getIpv4AccessListPolicyIngressInterface:getIpv4AccessListPolicyIngressInterface", args ?? new GetIpv4AccessListPolicyIngressInterfaceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetIpv4AccessListPolicyIngressInterfaceArgs : global::Pulumi.InvokeArgs
    {
        [Input("device")]
        public string? Device { get; set; }

        [Input("interfaceId", required: true)]
        public string InterfaceId { get; set; } = null!;

        public GetIpv4AccessListPolicyIngressInterfaceArgs()
        {
        }
        public static new GetIpv4AccessListPolicyIngressInterfaceArgs Empty => new GetIpv4AccessListPolicyIngressInterfaceArgs();
    }

    public sealed class GetIpv4AccessListPolicyIngressInterfaceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("device")]
        public Input<string>? Device { get; set; }

        [Input("interfaceId", required: true)]
        public Input<string> InterfaceId { get; set; } = null!;

        public GetIpv4AccessListPolicyIngressInterfaceInvokeArgs()
        {
        }
        public static new GetIpv4AccessListPolicyIngressInterfaceInvokeArgs Empty => new GetIpv4AccessListPolicyIngressInterfaceInvokeArgs();
    }


    [OutputType]
    public sealed class GetIpv4AccessListPolicyIngressInterfaceResult
    {
        public readonly string AccessListName;
        public readonly string? Device;
        public readonly string Id;
        public readonly string InterfaceId;

        [OutputConstructor]
        private GetIpv4AccessListPolicyIngressInterfaceResult(
            string accessListName,

            string? device,

            string id,

            string interfaceId)
        {
            AccessListName = accessListName;
            Device = device;
            Id = id;
            InterfaceId = interfaceId;
        }
    }
}
