// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Nxos.Nxos
{
    [NxosResourceType("nxos:nxos/nveVniContainer:NveVniContainer")]
    public partial class NveVniContainer : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Output("device")]
        public Output<string?> Device { get; private set; } = null!;


        /// <summary>
        /// Create a NveVniContainer resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NveVniContainer(string name, NveVniContainerArgs? args = null, CustomResourceOptions? options = null)
            : base("nxos:nxos/nveVniContainer:NveVniContainer", name, args ?? new NveVniContainerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NveVniContainer(string name, Input<string> id, NveVniContainerState? state = null, CustomResourceOptions? options = null)
            : base("nxos:nxos/nveVniContainer:NveVniContainer", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NveVniContainer resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NveVniContainer Get(string name, Input<string> id, NveVniContainerState? state = null, CustomResourceOptions? options = null)
        {
            return new NveVniContainer(name, id, state, options);
        }
    }

    public sealed class NveVniContainerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        public NveVniContainerArgs()
        {
        }
        public static new NveVniContainerArgs Empty => new NveVniContainerArgs();
    }

    public sealed class NveVniContainerState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        public NveVniContainerState()
        {
        }
        public static new NveVniContainerState Empty => new NveVniContainerState();
    }
}
