// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.nxos.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetDefaultQosPolicyInterfaceInPolicyMapResult {
    private @Nullable String device;
    private String id;
    private String interfaceId;
    private String policyMapName;

    private GetDefaultQosPolicyInterfaceInPolicyMapResult() {}
    public Optional<String> device() {
        return Optional.ofNullable(this.device);
    }
    public String id() {
        return this.id;
    }
    public String interfaceId() {
        return this.interfaceId;
    }
    public String policyMapName() {
        return this.policyMapName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDefaultQosPolicyInterfaceInPolicyMapResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String device;
        private String id;
        private String interfaceId;
        private String policyMapName;
        public Builder() {}
        public Builder(GetDefaultQosPolicyInterfaceInPolicyMapResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.device = defaults.device;
    	      this.id = defaults.id;
    	      this.interfaceId = defaults.interfaceId;
    	      this.policyMapName = defaults.policyMapName;
        }

        @CustomType.Setter
        public Builder device(@Nullable String device) {
            this.device = device;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder interfaceId(String interfaceId) {
            this.interfaceId = Objects.requireNonNull(interfaceId);
            return this;
        }
        @CustomType.Setter
        public Builder policyMapName(String policyMapName) {
            this.policyMapName = Objects.requireNonNull(policyMapName);
            return this;
        }
        public GetDefaultQosPolicyInterfaceInPolicyMapResult build() {
            final var o = new GetDefaultQosPolicyInterfaceInPolicyMapResult();
            o.device = device;
            o.id = id;
            o.interfaceId = interfaceId;
            o.policyMapName = policyMapName;
            return o;
        }
    }
}
