// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.nxos.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetEvpnVniResult {
    private @Nullable String device;
    private String encap;
    private String id;
    private String routeDistinguisher;

    private GetEvpnVniResult() {}
    public Optional<String> device() {
        return Optional.ofNullable(this.device);
    }
    public String encap() {
        return this.encap;
    }
    public String id() {
        return this.id;
    }
    public String routeDistinguisher() {
        return this.routeDistinguisher;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetEvpnVniResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String device;
        private String encap;
        private String id;
        private String routeDistinguisher;
        public Builder() {}
        public Builder(GetEvpnVniResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.device = defaults.device;
    	      this.encap = defaults.encap;
    	      this.id = defaults.id;
    	      this.routeDistinguisher = defaults.routeDistinguisher;
        }

        @CustomType.Setter
        public Builder device(@Nullable String device) {
            this.device = device;
            return this;
        }
        @CustomType.Setter
        public Builder encap(String encap) {
            this.encap = Objects.requireNonNull(encap);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder routeDistinguisher(String routeDistinguisher) {
            this.routeDistinguisher = Objects.requireNonNull(routeDistinguisher);
            return this;
        }
        public GetEvpnVniResult build() {
            final var o = new GetEvpnVniResult();
            o.device = device;
            o.encap = encap;
            o.id = id;
            o.routeDistinguisher = routeDistinguisher;
            return o;
        }
    }
}
