// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.nxos.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetEvpnVniRouteTargetResult {
    private @Nullable String device;
    private String direction;
    private String encap;
    private String id;
    private String routeTarget;

    private GetEvpnVniRouteTargetResult() {}
    public Optional<String> device() {
        return Optional.ofNullable(this.device);
    }
    public String direction() {
        return this.direction;
    }
    public String encap() {
        return this.encap;
    }
    public String id() {
        return this.id;
    }
    public String routeTarget() {
        return this.routeTarget;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetEvpnVniRouteTargetResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String device;
        private String direction;
        private String encap;
        private String id;
        private String routeTarget;
        public Builder() {}
        public Builder(GetEvpnVniRouteTargetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.device = defaults.device;
    	      this.direction = defaults.direction;
    	      this.encap = defaults.encap;
    	      this.id = defaults.id;
    	      this.routeTarget = defaults.routeTarget;
        }

        @CustomType.Setter
        public Builder device(@Nullable String device) {
            this.device = device;
            return this;
        }
        @CustomType.Setter
        public Builder direction(String direction) {
            this.direction = Objects.requireNonNull(direction);
            return this;
        }
        @CustomType.Setter
        public Builder encap(String encap) {
            this.encap = Objects.requireNonNull(encap);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder routeTarget(String routeTarget) {
            this.routeTarget = Objects.requireNonNull(routeTarget);
            return this;
        }
        public GetEvpnVniRouteTargetResult build() {
            final var o = new GetEvpnVniRouteTargetResult();
            o.device = device;
            o.direction = direction;
            o.encap = encap;
            o.id = id;
            o.routeTarget = routeTarget;
            return o;
        }
    }
}
