// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.nxos.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetNtpServerResult {
    private @Nullable String device;
    private String id;
    private Integer keyId;
    private Integer maxPoll;
    private Integer minPoll;
    private String name;
    private String type;
    private String vrf;

    private GetNtpServerResult() {}
    public Optional<String> device() {
        return Optional.ofNullable(this.device);
    }
    public String id() {
        return this.id;
    }
    public Integer keyId() {
        return this.keyId;
    }
    public Integer maxPoll() {
        return this.maxPoll;
    }
    public Integer minPoll() {
        return this.minPoll;
    }
    public String name() {
        return this.name;
    }
    public String type() {
        return this.type;
    }
    public String vrf() {
        return this.vrf;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNtpServerResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String device;
        private String id;
        private Integer keyId;
        private Integer maxPoll;
        private Integer minPoll;
        private String name;
        private String type;
        private String vrf;
        public Builder() {}
        public Builder(GetNtpServerResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.device = defaults.device;
    	      this.id = defaults.id;
    	      this.keyId = defaults.keyId;
    	      this.maxPoll = defaults.maxPoll;
    	      this.minPoll = defaults.minPoll;
    	      this.name = defaults.name;
    	      this.type = defaults.type;
    	      this.vrf = defaults.vrf;
        }

        @CustomType.Setter
        public Builder device(@Nullable String device) {
            this.device = device;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder keyId(Integer keyId) {
            this.keyId = Objects.requireNonNull(keyId);
            return this;
        }
        @CustomType.Setter
        public Builder maxPoll(Integer maxPoll) {
            this.maxPoll = Objects.requireNonNull(maxPoll);
            return this;
        }
        @CustomType.Setter
        public Builder minPoll(Integer minPoll) {
            this.minPoll = Objects.requireNonNull(minPoll);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        @CustomType.Setter
        public Builder vrf(String vrf) {
            this.vrf = Objects.requireNonNull(vrf);
            return this;
        }
        public GetNtpServerResult build() {
            final var o = new GetNtpServerResult();
            o.device = device;
            o.id = id;
            o.keyId = keyId;
            o.maxPoll = maxPoll;
            o.minPoll = minPoll;
            o.name = name;
            o.type = type;
            o.vrf = vrf;
            return o;
        }
    }
}
