// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nxos.nxos.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetRouteMapRuleEntryResult {
    private String action;
    private @Nullable String device;
    private String id;
    private Integer order;
    private String ruleName;

    private GetRouteMapRuleEntryResult() {}
    public String action() {
        return this.action;
    }
    public Optional<String> device() {
        return Optional.ofNullable(this.device);
    }
    public String id() {
        return this.id;
    }
    public Integer order() {
        return this.order;
    }
    public String ruleName() {
        return this.ruleName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRouteMapRuleEntryResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String action;
        private @Nullable String device;
        private String id;
        private Integer order;
        private String ruleName;
        public Builder() {}
        public Builder(GetRouteMapRuleEntryResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.action = defaults.action;
    	      this.device = defaults.device;
    	      this.id = defaults.id;
    	      this.order = defaults.order;
    	      this.ruleName = defaults.ruleName;
        }

        @CustomType.Setter
        public Builder action(String action) {
            this.action = Objects.requireNonNull(action);
            return this;
        }
        @CustomType.Setter
        public Builder device(@Nullable String device) {
            this.device = device;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder order(Integer order) {
            this.order = Objects.requireNonNull(order);
            return this;
        }
        @CustomType.Setter
        public Builder ruleName(String ruleName) {
            this.ruleName = Objects.requireNonNull(ruleName);
            return this;
        }
        public GetRouteMapRuleEntryResult build() {
            final var o = new GetRouteMapRuleEntryResult();
            o.action = action;
            o.device = device;
            o.id = id;
            o.order = order;
            o.ruleName = ruleName;
            return o;
        }
    }
}
