// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * This data source can read the Netflow feature configuration.
 *
 * - API Documentation: [fmNetflow](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Feature%20Management/fm:Netflow/)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nxos from "@pulumi/nxos";
 *
 * const example = nxos.getFeatureNetflow({});
 * ```
 */
export function getFeatureNetflow(args?: GetFeatureNetflowArgs, opts?: pulumi.InvokeOptions): Promise<GetFeatureNetflowResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nxos:index/getFeatureNetflow:getFeatureNetflow", {
        "device": args.device,
    }, opts);
}

/**
 * A collection of arguments for invoking getFeatureNetflow.
 */
export interface GetFeatureNetflowArgs {
    /**
     * A device name from the provider configuration.
     */
    device?: string;
}

/**
 * A collection of values returned by getFeatureNetflow.
 */
export interface GetFeatureNetflowResult {
    /**
     * Administrative state.
     */
    readonly adminState: string;
    /**
     * A device name from the provider configuration.
     */
    readonly device?: string;
    /**
     * The distinguished name of the object.
     */
    readonly id: string;
}
/**
 * This data source can read the Netflow feature configuration.
 *
 * - API Documentation: [fmNetflow](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Feature%20Management/fm:Netflow/)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nxos from "@pulumi/nxos";
 *
 * const example = nxos.getFeatureNetflow({});
 * ```
 */
export function getFeatureNetflowOutput(args?: GetFeatureNetflowOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetFeatureNetflowResult> {
    return pulumi.output(args).apply((a: any) => getFeatureNetflow(a, opts))
}

/**
 * A collection of arguments for invoking getFeatureNetflow.
 */
export interface GetFeatureNetflowOutputArgs {
    /**
     * A device name from the provider configuration.
     */
    device?: pulumi.Input<string>;
}
