// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * This data source can read the queuing QoS policy system out configuration.
 *
 * - API Documentation: [ipqosSystem](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Qos/ipqos:System/)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nxos from "@pulumi/nxos";
 *
 * const example = nxos.getQueuingQosPolicySystemOut({});
 * ```
 */
export function getQueuingQosPolicySystemOut(args?: GetQueuingQosPolicySystemOutArgs, opts?: pulumi.InvokeOptions): Promise<GetQueuingQosPolicySystemOutResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nxos:index/getQueuingQosPolicySystemOut:getQueuingQosPolicySystemOut", {
        "device": args.device,
    }, opts);
}

/**
 * A collection of arguments for invoking getQueuingQosPolicySystemOut.
 */
export interface GetQueuingQosPolicySystemOutArgs {
    /**
     * A device name from the provider configuration.
     */
    device?: string;
}

/**
 * A collection of values returned by getQueuingQosPolicySystemOut.
 */
export interface GetQueuingQosPolicySystemOutResult {
    /**
     * A device name from the provider configuration.
     */
    readonly device?: string;
    /**
     * The distinguished name of the object.
     */
    readonly id: string;
}
/**
 * This data source can read the queuing QoS policy system out configuration.
 *
 * - API Documentation: [ipqosSystem](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Qos/ipqos:System/)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nxos from "@pulumi/nxos";
 *
 * const example = nxos.getQueuingQosPolicySystemOut({});
 * ```
 */
export function getQueuingQosPolicySystemOutOutput(args?: GetQueuingQosPolicySystemOutOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetQueuingQosPolicySystemOutResult> {
    return pulumi.output(args).apply((a: any) => getQueuingQosPolicySystemOut(a, opts))
}

/**
 * A collection of arguments for invoking getQueuingQosPolicySystemOut.
 */
export interface GetQueuingQosPolicySystemOutOutputArgs {
    /**
     * A device name from the provider configuration.
     */
    device?: pulumi.Input<string>;
}
